# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    # Loop over all 2023 folders and add a black input.txt file
    - name: Create input.txt files
      run: |
        for d in 2023/*; do
          touch $d/input.txt
        done

    - name: Vet
      run: go vet ./...

    - name: Build
      run: go build ./...

    - name: Test
      run: go test ./...
